### ISSUE TITLE
省略カラーコードの対応

### ISSUE THREAD

**Issue by sevenc-nanashi** [Yamamoto0773/GCSimulator.App#54]
cssなどでは#fffで#ffffff, #aabbで#aaaabbbbという感じで入力できるので対応して欲しい。

**Comment by Yamamoto0773** [comment]
3桁or4桁の16進数表記いいですね。v0.2.8で対応します 👍

**Comment by Yamamoto0773** [comment]
対応完了．v0.2.8で導入
